FROM node:22-slim AS web-build

WORKDIR /app

COPY web/package.json web/package-lock.json ./
RUN npm ci

COPY web/ ./
RUN npm run build


FROM node:22-slim

WORKDIR /app

RUN npm install -g serve@14.2.4

COPY --from=web-build /app/dist ./dist

CMD ["serve", "-s", "dist", "-l", "3030"]
