FROM mcr.microsoft.com/playwright:v1.59.1-noble

WORKDIR /app

COPY web/package.json web/package-lock.json ./
RUN npm ci

COPY web/playwright.config.ts ./
COPY web/e2e/ ./e2e/
COPY web/tsconfig.json ./

CMD ["npx", "playwright", "test"]
